# Change these first
owner: 51sec # Your GitHub organization or username, where this repository lives
repo: up # The name of this repository

sites:
  - name: Blog
    url: https://blog.51sec.org
  - name: WWW
    url: https://www.51sec.org
  - name: ITPROSEC
    url: https://www.itprosec.com
  - name: Sites
    url: https://www.itprosec.com
  - name: Google
    url: https://www.google.com


status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: up.51sec.org
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/51sec/up/master/assets/up-icon.png
  name: UP
  introTitle: "**UP** monitoring and showing status of 51Sec Websites."
  introMessage: Monitoring **real-time** data from our [GitHub repository](https://github.com/51sec/up).
  navbar:
    - title: Status for 51Sec Sites and Servers
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
