# Change these first
owner: 51sec # Your GitHub organization or username, where this repository lives
repo: up # The name of this repository

sites:
  - name: Blog
    url: https://blog.51sec.org
    icon: https://blog.51sec.org/favicon.ico
  - name: WWW
    url: https://www.51sec.org
    icon: https://www.51sec.org/favicon.ico
  - name: ITPROSEC
    url: https://www.itprosec.com
    icon: https://itprosec.com/wp-content/uploads/2020/03/ITPROSEC-No-Transparent-Icon-Only-small.jpg
  - name: Sites
    url: https://sites.51sec.org
    icon: https://photos.51sec.org/file/test1-51sec/2021/10/sites%20-%20round%20-500.png
  - name: Navigation
    url: https://nav.51sec.org
    icon: https://photos.51sec.org/file/test1-51sec/2021/10/Black%2C%20White%20and%20Yellow%20Lightning%20-%20Round%20corner-350.png
  - name: OneDrive
    url: https://od.51sec.org
    icon: https://photos.51sec.org/file/test1-51sec/2021/10/OneDrive%20OD%2051sec-roundcorner%20-%20Copy.png
  - name: NetSec YouTube Channel
    url: https://www.youtube.com/c/NetSec
    icon: https://image.similarpng.com/very-thumbnail/2020/05/Logo-YouTube-realistic-icon-transparent-PNG.png
  - name: Google DNS 8.8.8.8
    check: "tcp-ping"
    url: 8.8.8.8
    port: 53
    icon: https://icons.veryicon.com/png/o/application/app-general-icon-01/dns-1.png


status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: up.51sec.org
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/51sec/up/master/assets/up-icon.png
  name: UP
  introTitle: "**UP** monitors 51Sec Websites and servers!"
  introMessage: The monitoring **real-time** data from our [GitHub repository](https://github.com/51sec/up).
  favicon: https://raw.githubusercontent.com/51sec/up/master/assets/up-icon.png
  theme: ocean
  # Available themes are light, dark, night or ocean.
  navbar:
    - title: Status Page
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
    - title: 51Sec
      href: https://blog.51sec.org

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
